[general]
# The mode for the signup. Default: "token_required" Options:
# "open" - anyone can signup.
# "token_required" - a signup token is required to signup.
signup_mode = "token_required"
database_url ="postgres://test_user:test_pass@172.18.0.9:5432/pubky_homeserver?pubky_test=true"

[pkdns]
icann_domain = "localhost"
public_ip = "172.18.0.4"

[derive]
testnet_host = "homeserver"
